# git inventory (yaml)
---
all:
  hosts:
    #gihub work
    github:
      ansible_host: "ssh.github.com"
      ansible_user: "git"
      ansible_ssh_private_key_file: "ssh_key_work"
      Port: "443"
      ForwardAgent: "no" 
      ForwardX11: "no"
      IdentitiesOnly: "yes"
    # github private 
    githubv:
      ansible_host: "ssh.github.com"
      ansible_user: "git"
      ansible_ssh_private_key_file: "ssh_key_private"
      Port: "443"
      ForwardAgent: "no" 
      ForwardX11: "no"
      IdentitiesOnly: "yes"
  children:
    repos:
      hosts:
        github:
        githubv:
